version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5ebCDZfroh48eo
      MYSQL_DATABASE: Bank_DB
      MYSQL_USER: Empathy0465
      MYSQL_PASSWORD: d2Qj2YN9xySPry
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
